<?php
/**
 * Super Page Cache for Cloudflare Testing Items.
 *
 * @package Themeisle_Tester
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Registers read-only inspect utilities for the Super Page Cache plugin.
 */
class TTP_Addon_Super_Page_Cache implements TTP_Addon {

	/**
	 * Register Super Page Cache Testing Items.
	 *
	 * @param TTP_Item_Registry $registry Item registry.
	 * @return void
	 */
	public function register( TTP_Item_Registry $registry ) {
		$registry->register(
			array(
				'id'              => 'spc_cached_files',
				'type'            => 'utility',
				'categories'      => array( __( 'SPC', 'themeisle-tester' ) ),
				'product'         => __( 'Super Page Cache for Cloudflare', 'themeisle-tester' ),
				'label'           => __( 'Cached HTML files', 'themeisle-tester' ),
				'description'     => __( 'Lists the HTML files generated by Super Page Cache fallback cache, with size and modified time. Click View to open the cached file in a new tab.', 'themeisle-tester' ),
				'width'           => 'full',
				'requires'        => TTP_Integration_Checks::require_super_page_cache(),
				'inspect'         => array( $this, 'inspect_cached_files' ),
				'render_inspect'  => array( $this, 'render_inspect_cached_files' ),
				'inspect_on_load' => false,
				'inspect_refresh' => true,
			)
		);
	}

	/**
	 * Inspect cached HTML files written by Super Page Cache fallback cache.
	 *
	 * @param array<string,mixed> $item    Item definition.
	 * @param array<string,mixed> $payload Sanitized inspect payload (unused).
	 * @return array<string,mixed>|WP_Error
	 */
	public function inspect_cached_files( $item, $payload ) {
		unset( $payload );

		if ( ! TTP_Integration_Checks::meets_item_requirements( $item ) ) {
			return new WP_Error( 'ttp_spc_unavailable', TTP_Integration_Checks::unavailable_reason_for_item( $item ) );
		}

		$directory = $this->get_cache_directory();

		if ( '' === $directory || ! is_dir( $directory ) ) {
			return array(
				'directory'        => $directory,
				'directory_exists' => false,
				'total'            => 0,
				'files'            => array(),
			);
		}

		$paths = glob( trailingslashit( $directory ) . '*.html' );

		if ( ! is_array( $paths ) ) {
			$paths = array();
		}

		$files = array();

		foreach ( $paths as $path ) {
			$entry = $this->build_file_entry( $path );

			if ( null !== $entry ) {
				$files[] = $entry;
			}
		}

		usort(
			$files,
			static function ( $left, $right ) {
				return $right['mtime'] <=> $left['mtime'];
			}
		);

		return array(
			'directory'        => $directory,
			'directory_exists' => true,
			'total'            => count( $files ),
			'files'            => $files,
		);
	}

	/**
	 * Render the cached-files inspect output.
	 *
	 * @param array<string,mixed> $item           Item definition.
	 * @param mixed               $inspect_result Inspect callback result.
	 * @param TTP_Admin_Page      $page           Admin page.
	 * @return void
	 */
	public function render_inspect_cached_files( $item, $inspect_result, TTP_Admin_Page $page ) {
		unset( $item );
		$page->render_spc_cached_files( $inspect_result );
	}

	/**
	 * Resolve the Super Page Cache fallback-cache directory for this site.
	 *
	 * Mirrors the path produced by SPC\Utils\Helpers::get_plugin_content_dir() +
	 * SPC\Modules\Fallback_Cache::fallback_cache_init_directory(). Resolved
	 * locally to avoid depending on the SPC plugin's namespaced internals.
	 *
	 * @return string
	 */
	private function get_cache_directory() {
		if ( ! defined( 'WP_CONTENT_DIR' ) ) {
			return '';
		}

		$host = wp_parse_url( home_url(), PHP_URL_HOST );

		if ( ! is_string( $host ) || '' === $host ) {
			return '';
		}

		return WP_CONTENT_DIR . '/wp-cloudflare-super-page-cache/' . $host . '/fallback_cache';
	}

	/**
	 * Build a single file entry for the inspect payload.
	 *
	 * @param string $path Absolute filesystem path.
	 * @return array<string,mixed>|null
	 */
	private function build_file_entry( $path ) {
		if ( '' === $path ) {
			return null;
		}

		if ( ! is_file( $path ) ) {
			return null;
		}

		$size  = filesize( $path );
		$mtime = filemtime( $path );

		if ( false === $size ) {
			$size = 0;
		}

		if ( false === $mtime ) {
			$mtime = 0;
		}

		$name        = basename( $path );
		$mtime_human = $mtime > 0 ? (string) wp_date( 'Y-m-d H:i:s', $mtime ) : '';
		$size_human  = size_format( $size, 1 );

		if ( '' === $size_human ) {
			$size_human = (string) $size . ' B';
		}

		return array(
			'name'        => $name,
			'size'        => (int) $size,
			'size_human'  => $size_human,
			'mtime'       => (int) $mtime,
			'mtime_human' => $mtime_human,
			'url'         => $this->build_file_url( $path ),
		);
	}

	/**
	 * Build the public URL for a cached file living under WP_CONTENT_DIR.
	 *
	 * @param string $path Absolute filesystem path.
	 * @return string
	 */
	private function build_file_url( $path ) {
		if ( ! defined( 'WP_CONTENT_DIR' ) ) {
			return '';
		}

		$content_dir = wp_normalize_path( WP_CONTENT_DIR );
		$normalized  = wp_normalize_path( $path );

		if ( 0 !== strpos( $normalized, $content_dir ) ) {
			return '';
		}

		$relative = ltrim( substr( $normalized, strlen( $content_dir ) ), '/' );

		if ( '' === $relative ) {
			return '';
		}

		return content_url( $relative );
	}
}
